/**
 * Prompt/context assembly.
 *
 * Ported from `build_agent_context` in
 * apps/desktop/src-tauri/src/agent/context.rs plus the loop/final prompt
 * builders in agent/runtime.rs. Every block is host-owned structure around
 * untrusted content: file bodies and skill text are XML-escaped, and each
 * section is truncated on a character budget so a single large attachment or
 * observation cannot displace the rest of the context.
 */
import { Domain } from 'llm-wiki-protocol'
import {
  collapseWhitespace,
  escapeXml,
  MAX_AUTO_SKILL_INDEX_CHARS,
  MAX_AUTO_SKILLS,
  MAX_EXPLICIT_CONTEXT_CHARS,
  MAX_HISTORY_CHARS,
  MAX_OVERVIEW_CHARS,
  MAX_REFERENCE_CHARS,
  MAX_SCHEMA_CHARS,
  MAX_SKILL_CHARS,
  trimChars,
} from './project.js'
import type { ProjectContext } from './project.js'
import type { RouterDecision } from './router.js'
import type { AgentSkill } from './skills.js'

export interface AgentObservation {
  readonly tool: string
  readonly summary: string
}

export interface AgentContextInput {
  readonly query: string
  readonly project: ProjectContext
  readonly router: RouterDecision
  readonly history: ReadonlyArray<{ readonly role: string; readonly content: string }>
  readonly skills: ReadonlyArray<AgentSkill>
  readonly skillMode: Domain.AgentSkillMode
  readonly references: ReadonlyArray<Domain.ChatReference>
  readonly retrievalSummary: string
  readonly explicitFiles: ReadonlyArray<readonly [string, string]>
}

export interface BuiltAgentContext {
  readonly system: string
  readonly user: string
}

const renderAvailableSkills = (skills: ReadonlyArray<AgentSkill>): string => {
  let out = '\n<available_skills>\n'
  let rendered = 0
  for (const skill of skills.slice(0, MAX_AUTO_SKILLS)) {
    const entry = `  <skill>\n    <name>${escapeXml(skill.name)}</name>\n    <description>${
      escapeXml(skill.description.trim())
    }</description>\n    <location>${escapeXml(skill.location)}</location>\n  </skill>\n`
    if (Array.from(out).length + Array.from(entry).length > MAX_AUTO_SKILL_INDEX_CHARS) break
    out += entry
    rendered += 1
  }
  if (rendered < skills.length) {
    out += `  <omitted>${
      skills.length - rendered
    } additional skill(s) omitted from the automatic index. Explicitly select a skill to include its full instructions.</omitted>\n`
  }
  return `${out}</available_skills>\n`
}

const renderExplicitSkill = (skill: AgentSkill): string =>
  `\n<skill name="${escapeXml(skill.name)}" location="${
    escapeXml(skill.location)
  }">\nReferences are relative to ${skill.baseDir}.\n\n${skill.instructions.trim()}\n</skill>`

const buildSystemContext = (
  project: ProjectContext,
  router: RouterDecision,
  skills: ReadonlyArray<AgentSkill>,
  skillMode: Domain.AgentSkillMode,
): string => {
  let out = [
    'You are the LLM Wiki backend Agent.',
    'Answer using the current project context, available tools, and cited references.',
    'If evidence is insufficient, say what is missing instead of inventing facts.',
    'When using references, mention the relevant page paths naturally.',
    'Do not claim that internet or local-source search is unavailable when those tools are enabled; use the provided tool context and tool hints.',
  ].join('\n')

  out += '\n\nTool policy:\n'
  out += '- wiki.search retrieves pages for factual or topical questions.\n'
  out +=
    '- graph.search retrieves relationships, neighbors, backlinks, dependencies, and connections between project entities. Prefer it when the requested answer is about how concepts or entities relate, and use concise entity names rather than the full natural-language question.\n'
  if (router.shouldHintWeb) {
    out += '- web.search is available when current or external information is useful.\n'
  }
  if (router.shouldHintAnytxt) {
    out += '- anytxt.search is available for local or remote file content indexed by AnyTXT.\n'
  }
  out += `- Router hint: ${router.intent}. ${router.rationale}\n`
  out += '\nGenerated file policy:\n'
  out +=
    `- All files generated by the Agent, skills, shell commands, scripts, image tools, HTML exports, or any future generation feature must be created under this visible project workspace: ${project.agentWorkspace}.\n`
  out +=
    "- Do not create generated files in the user's home folder, Desktop, Downloads, system temp folders, hidden app metadata folders, or skill installation folders.\n"
  out +=
    '- Treat skill folders as read-only instruction/reference sources. If a skill or script needs output files, pass or choose a path under the Agent workspace above.\n'
  out +=
    '- If the requested visual can be represented as a Mermaid diagram, reply with a ```mermaid fenced code block directly instead of generating an HTML file just to display that diagram.\n'
  out +=
    '- When using shell.exec, prefer relative output paths because the shell runs from the Agent workspace; use the LLM_WIKI_AGENT_WORKSPACE environment variable when an absolute output path is required.\n'

  if (project.overview !== undefined && project.overview.trim() !== '') {
    out += '\n\nProject overview:\n'
    out += trimChars(project.overview, MAX_OVERVIEW_CHARS)
  }
  if (project.schema !== undefined && project.schema.trim() !== '') {
    out += '\n\nProject schema:\n'
    out += trimChars(project.schema, MAX_SCHEMA_CHARS)
  }
  if (skills.length > 0) {
    if (skillMode === 'explicit') {
      out += '\n\nSelected skills:\n'
      out +=
        "The user explicitly selected the following skill instructions for this turn. Treat them as task-specific instructions and apply them unless they conflict with safety, project boundaries, or the user's latest request. Supporting files should still be read lazily from the listed skill directory only when needed.\n"
      let remaining = MAX_SKILL_CHARS
      for (const skill of skills) {
        if (remaining === 0) break
        const piece = trimChars(renderExplicitSkill(skill), remaining)
        remaining -= Array.from(piece).length
        out += piece
        out += '\n'
      }
    } else {
      out += '\n\nThe following skills provide specialized instructions for specific tasks.\n'
      out +=
        'Use a skill only when the latest request matches its description. To inspect a skill, use the listed SKILL.md location; when a skill references a relative path, resolve it against the skill directory.\n'
      out += renderAvailableSkills(skills)
    }
  }
  return out
}

const renderReference = (reference: Domain.ChatReference, index: number): string => {
  let rendered = `${index}. [${reference.kind}] ${reference.title} (${reference.path})\n`
  if (reference.snippet !== undefined) {
    rendered += `Snippet: ${collapseWhitespace(reference.snippet)}\n`
  }
  const context = reference.knowledgeContext
  if (context !== undefined) {
    if (context.relatedTo !== undefined && context.relatedTo.length > 0) {
      rendered += `Graph neighbors of: ${context.relatedTo.join(', ')}\n`
    }
    if (context.tags !== undefined && context.tags.length > 0) {
      rendered += `Tags: ${context.tags.join(', ')}\n`
    }
    if (context.outgoingLinks !== undefined && context.outgoingLinks.length > 0) {
      rendered += `Links to: ${context.outgoingLinks.join(', ')}\n`
    }
    if (context.backlinks !== undefined && context.backlinks.length > 0) {
      rendered += `Backlinks: ${context.backlinks.join(', ')}\n`
    }
    rendered += `Related links: ${context.linkCount}\n`
    if (context.latestVersion !== undefined) {
      rendered +=
        `Latest version: ${context.latestVersion.author} via ${context.latestVersion.tool} at ${context.latestVersion.timestamp}\n`
    }
  }
  return rendered
}

const buildUserContext = (input: AgentContextInput): string => {
  let out = ''
  if (input.history.length > 0) {
    out += 'Recent conversation history:\n'
    let history = ''
    for (const item of input.history.slice(-12)) {
      history += `${item.role}: ${collapseWhitespace(item.content)}\n`
    }
    out += trimChars(history, MAX_HISTORY_CHARS)
    out += '\n\n'
  }

  if (input.explicitFiles.length > 0) {
    out += 'User-selected project files:\n'
    let remaining = MAX_EXPLICIT_CONTEXT_CHARS
    for (const [path, content] of input.explicitFiles) {
      if (remaining === 0) break
      const prefix = `\n<file path="${escapeXml(path)}">\n`
      const suffix = '\n</file>\n'
      const overhead = Array.from(prefix).length + Array.from(suffix).length
      if (remaining <= overhead) break
      const body = trimChars(escapeXml(content), remaining - overhead)
      out += prefix
      out += body
      out += suffix
      remaining -= overhead + Array.from(body).length
    }
    out += '\n\n'
  }

  out += 'Retrieved project context:\n'
  if (input.references.length === 0) {
    out += 'No matching wiki references were found.\n\n'
  } else {
    let rendered = ''
    input.references.forEach((reference, index) => {
      rendered += renderReference(reference, index + 1)
    })
    out += trimChars(rendered, MAX_REFERENCE_CHARS)
    out += '\n'
  }

  out += 'Retrieval summary:\n'
  out += trimChars(input.retrievalSummary, 8_000)
  out += '\n\nLatest user request:\n'
  out += input.query.trim()
  return out
}

export const buildAgentContext = (input: AgentContextInput): BuiltAgentContext => ({
  system: buildSystemContext(input.project, input.router, input.skills, input.skillMode),
  user: buildUserContext(input),
})

export const buildAgentLoopSystem = (
  baseSystem: string,
  retrievalMode: Domain.AgentRetrievalMode,
): string => {
  const smartRetrieval = retrievalMode === 'smart'
    ? '\nSmart retrieval is enabled. Treat retrieval as a bounded evidence loop: after every observation, identify only the unresolved evidence gap, then either issue one concise revised retrieval action or answer. Prefer reading/following already discovered pages before broadening the query. Do not repeat equivalent queries. Stop as soon as the available evidence supports a cited answer; optional background is not a reason to continue.'
    : ''
  const faithfulRetrieval = retrievalMode === 'faithful'
    ? '\nFaithful-source mode is enabled by explicit user choice. Answer only from raw source excerpts returned by source.search or explicitly attached source files. Preserve quoted wording exactly and cite the source path beside every quotation or factual claim. Clearly distinguish verbatim quotations from explanation. Generated wiki pages, graph context, web results, AnyTXT results, and unsupported background knowledge are not evidence in this mode. If the available excerpts are insufficient, state that limitation instead of reconstructing or guessing.'
    : ''
  const retrievalExample = retrievalMode === 'faithful'
    ? '1. {"action":"tool","tool":"source.search","query":"..."}'
    : '1. {"action":"tool","tool":"wiki.search","query":"..."}'
  return `${baseSystem}\n\nAgent loop protocol:\nReturn only compact JSON. Do not wrap it in markdown.\nChoose exactly one action per turn:\n${retrievalExample}\n2. {"action":"tool","tool":"user.ask","title":"...","description":"...","fields":[{"id":"choice","type":"single","label":"...","options":[{"label":"...","value":"...","recommended":true}]}]}\n3. {"action":"tool","tool":"workspace.write_file","path":"cover-image/cover.svg","content":"..."}\n3b. {"action":"tool","tool":"workspace.append_file","path":"deck/index.html","content":"..."}\n4. {"action":"final","answer":"..."}\nUse tools when they are useful, then wait for the observation in the next turn before deciding the next step.\nDo not return natural-language plans such as "I need to read..." or "Let me search...". If you intend to read/search/write/run something, return the matching tool JSON action in this turn.\nDo not merely announce that you will use a skill or tool. If a skill references a file under its own directory, call skill.read_file with a relative path. If a skill requires an actual command-line generation step, call shell.exec.\nUse skill.read_file for skill Markdown/reference files. Do not use shell.exec, test, cat, or ls merely to inspect skill files or optional preference files.\nUse user.ask when a skill or task needs structured user choices, text input, confirmations, or multiple fields before it can continue. Do not simulate this by writing plain-text questions when a structured form is appropriate.\nUse workspace.write_file for generated artifacts such as SVG, HTML, Markdown drafts, JSON, or scripts. For large HTML/PPT files, first call workspace.write_file with an empty or small opening chunk, then call workspace.append_file with subsequent chunks, and finish only after the file contains closing tags such as </html>. Do not inline large heredocs or generated file bodies inside shell.exec JSON.\nDo not claim that a generated file exists until a workspace.write_file or shell.exec observation confirms it. In the final answer, mention only observed generated file paths.\nConverge quickly. Do not keep reading optional references, running optional validation, or polishing after the requested deliverable has been written. Prefer final as soon as the core user request is satisfied.\nOnly use shell.exec when active skill instructions or the user's explicit request require command-line work after files have been written with workspace.write_file. Generated files must be written under the Agent workspace described above. Commands whose explicit file paths stay inside the Agent workspace can run without an approval prompt; commands that mention external paths, home directories, downloads, temp folders, or network URLs require approval.\nUse wiki.write_page only when the user explicitly asks to create or update a wiki page. Existing pages are create-only unless allowOverwrite is explicitly justified by the user's request.${smartRetrieval}${faithfulRetrieval}`
}

export const buildAgentFinalSystem = (
  baseSystem: string,
  retrievalMode: Domain.AgentRetrievalMode,
): string => {
  const faithfulRetrieval = retrievalMode === 'faithful'
    ? ' Faithful-source mode remains in force: use only raw source excerpts or explicitly attached source files as evidence, cite their paths, preserve quotations exactly, and disclose insufficient evidence rather than guessing.'
    : ''
  return `${baseSystem}\n\nThe retrieval phase is complete. No tools are available now. Answer the user's latest request directly using the permitted context and tool observations already provided.${faithfulRetrieval} Return only compact JSON in the form {"action":"final","answer":"..."}. Do not request, announce, or simulate another search or file read.`
}

export const renderObservations = (observations: ReadonlyArray<AgentObservation>): string => {
  if (observations.length === 0) return ''
  return observations
    .map((observation, index) => `${index + 1}. ${observation.tool}:\n${trimChars(observation.summary, 8_000)}`)
    .join('\n\n')
}

export const buildAgentFinalUser = (
  baseUser: string,
  observations: ReadonlyArray<AgentObservation>,
): string => {
  let out = baseUser
  if (observations.length > 0) {
    out += '\n\nCompleted tool observations:\n'
    out += renderObservations(observations)
  }
  out += '\n\nProvide the final answer now. No further tool action is permitted.'
  return out
}

export interface AgentToolHints {
  readonly wiki: boolean
  readonly web: boolean
  readonly anytxt: boolean
}

export const buildAgentLoopUser = (
  baseUser: string,
  tools: AgentToolHints,
  retrievalMode: Domain.AgentRetrievalMode,
  skills: ReadonlyArray<AgentSkill>,
  observations: ReadonlyArray<AgentObservation>,
  iteration: number,
  maxIterations: number,
  hasGeneratedWorkspaceFile: boolean,
): string => {
  let out = baseUser
  out += '\n\nAvailable Agent tools for this turn:\n'
  if (tools.wiki) {
    if (retrievalMode === 'faithful') {
      out +=
        '- source.search: search raw source excerpts. This is the only retrieval tool permitted in faithful-source mode.\n'
    } else {
      out += '- wiki.search: retrieve wiki pages for factual or topical questions.\n'
      out += '- wiki.read_page: read a specific wiki markdown page by path.\n'
      out += '- source.search: search raw source snippets.\n'
      out +=
        '- graph.search: retrieve relationships, neighbors, backlinks, dependencies, and connections between entities. Prefer it for relational questions and query with concise entity or concept names.\n'
      out += '- wiki.write_page: create a wiki markdown page when explicitly requested.\n'
    }
  }
  if (tools.web && retrievalMode !== 'faithful') {
    out += '- web.search: search external web sources.\n'
  }
  if (tools.anytxt && retrievalMode !== 'faithful') {
    out += '- anytxt.search: search files indexed by AnyTXT.\n'
  }
  if (skills.length > 0) {
    out +=
      '- skill.read_file: read a Markdown/reference file from an active skill directory by relative path. Prefer this over shell.exec for skill references.\n'
    out +=
      '- user.ask: pause and show the user a structured form with single-choice, multi-choice, text, textarea, or confirmation fields when an active skill needs user input.\n'
    out +=
      '- workspace.write_file: write generated artifacts under agent-workspace by relative path. For large HTML/PPT, initialize the file and then append chunks.\n'
    out +=
      '- workspace.append_file: append content to a generated artifact under agent-workspace. Prefer this for large HTML/PPT after workspace.write_file.\n'
    out +=
      '- shell.exec: run a command from the Agent workspace when a selected/available skill requires command-line work. Workspace-local commands can run directly; external paths or network access require approval.\n'
  }
  if (observations.length === 0) {
    out += '\nTool observations so far: none.\n'
  } else {
    out += '\nTool observations so far:\n'
    out += renderObservations(observations)
    out += '\n'
  }
  const stepNumber = iteration + 1
  const remainingAfterThis = Math.max(0, maxIterations - stepNumber)
  out +=
    `\nIteration budget: step ${stepNumber} of ${maxIterations}. You have ${remainingAfterThis} step(s) after this response.\n`
  if (hasGeneratedWorkspaceFile) {
    out +=
      'A generated workspace file has already been observed. If it satisfies the core request, return final now with the file path. Do not spend remaining steps on optional validation or extra reference reads unless the user explicitly required them.\n'
  }
  if (remainingAfterThis <= 2) {
    out +=
      'Budget is nearly exhausted. Return final now if any useful answer or generated file exists. Use at most one more tool only when it is strictly required to complete or close an already-started file; skip optional checks, optional reads, and style polishing.\n'
  }
  out +=
    '\nReturn the next JSON action now. Prefer {"action":"final","answer":"..."} whenever the core request is already satisfied.'
  return out
}

export const looksLikeAgentToolJson = (value: string): boolean => {
  const trimmed = value.trimStart()
  return trimmed.startsWith('{') &&
    (trimmed.includes('"action"') || trimmed.includes('"tool"') || trimmed.includes('"command"'))
}

export const forcedFinalAnswer = (
  raw: string,
  action: { readonly action: string; readonly answer?: string | undefined },
  references: ReadonlyArray<Domain.ChatReference>,
): string => {
  if (action.action.toLowerCase() === 'final') {
    const answer = action.answer?.trim() ?? ''
    if (answer !== '') return answer
  }
  const trimmed = raw.trim()
  if (trimmed !== '' && !looksLikeAgentToolJson(trimmed)) return trimmed
  if (references.length === 0) {
    return 'I could not find enough project context to answer this request reliably.'
  }
  let answer = 'I found the following relevant project context:\n'
  for (const reference of references.slice(0, 8)) {
    answer += `- ${reference.title} (${reference.path})`
    if (reference.snippet !== undefined) {
      answer += `: ${trimChars(collapseWhitespace(reference.snippet), 320)}`
    }
    answer += '\n'
  }
  return answer
}

export const agentIterationLimitAnswer = (
  maxIterations: number,
  observationCount: number,
  references: ReadonlyArray<Domain.ChatReference>,
): string => {
  const seen = new Set<string>()
  const workspacePaths: Array<string> = []
  for (const reference of references) {
    if (reference.kind !== 'workspace' || reference.path.trim() === '') continue
    if (seen.has(reference.path)) continue
    seen.add(reference.path)
    workspacePaths.push(reference.path)
  }

  if (workspacePaths.length === 0) {
    return `The Agent reached the tool-iteration limit after ${maxIterations} step(s). It gathered ${observationCount} tool observation(s), but did not produce a final answer. Please narrow the request or ask it to continue from the latest result.`
  }

  let answer =
    `The Agent reached the tool-iteration budget after ${maxIterations} step(s), but it did generate file(s).\n\nGenerated files:\n`
  for (const path of workspacePaths) answer += `- ${path}\n`
  answer +=
    '\nOpen the generated file reference(s) to preview them. Some optional validation or follow-up steps may not have completed.'
  return answer
}
