import type { ApiErrorTag, EmbedErrorKind } from './errors.schema.js'

export interface RetiredStatusSite {
  readonly status: number | null
  readonly site: string
  readonly error: ApiErrorTag | null
  readonly embedKind?: EmbedErrorKind
}

export const RETIRED_STATUS_SITES: ReadonlyArray<RetiredStatusSite> = [
  { status: 400, site: 'process_request: read_body failure', error: 'InvalidRequest' },
  { status: 429, site: 'start_api_server: rate limit window exhausted', error: 'RateLimited' },
  { status: 503, site: 'start_api_server: in-flight request slot exhausted', error: 'Busy' },
  { status: 401, site: 'process_request: streaming chat token check', error: 'Unauthorized' },
  { status: 404, site: 'process_request: streaming chat route match', error: 'NotFound' },
  { status: 503, site: 'process_request: chat stream slot exhausted', error: 'Busy' },
  { status: 500, site: 'process_request: handler panic', error: null },
  { status: 404, site: 'handle_request: path outside /api/v1', error: 'NotFound' },
  { status: 503, site: 'handle_request: api_enabled kill switch', error: 'ApiDisabled' },
  { status: 401, site: 'handle_request: always-token request rejected', error: 'Unauthorized' },
  { status: 401, site: 'handle_request: auth required and token rejected', error: 'Unauthorized' },
  { status: 405, site: 'handle_request: method outside GET/POST/PATCH', error: null },
  { status: 404, site: 'handle_request: unparsable api path', error: 'NotFound' },
  { status: 404, site: 'handle_request: no route matched', error: 'NotFound' },
  { status: 404, site: 'handle_files: project resolution', error: 'NotFound' },
  { status: 400, site: 'handle_files: root selector', error: 'InvalidRequest' },
  { status: 400, site: 'handle_files: safe_join rejection', error: 'PathViolation' },
  { status: 413, site: 'handle_files: maxFiles listing cap', error: 'TooLarge' },
  { status: 500, site: 'handle_files: directory listing failure', error: null },
  { status: 404, site: 'handle_file_content: project resolution', error: 'NotFound' },
  { status: 400, site: 'handle_file_content: missing path parameter', error: 'InvalidRequest' },
  { status: 403, site: 'handle_file_content: path outside public roots', error: 'PathViolation' },
  { status: 415, site: 'handle_file_content: extension outside text allow-list', error: 'UnsupportedMediaType' },
  { status: 400, site: 'handle_file_content: safe_join rejection', error: 'PathViolation' },
  { status: 404, site: 'handle_file_content: file metadata missing', error: 'NotFound' },
  { status: 413, site: 'handle_file_content: 2 MiB content cap', error: 'TooLarge' },
  { status: 415, site: 'handle_file_content: invalid UTF-8 payload', error: 'UnsupportedMediaType' },
  { status: 404, site: 'handle_reviews: project resolution', error: 'NotFound' },
  { status: 400, site: 'handle_reviews: status filter value', error: 'InvalidRequest' },
  { status: 500, site: 'handle_reviews: review store read failure', error: null },
  { status: 404, site: 'handle_patch_review: project resolution', error: 'NotFound' },
  { status: 400, site: 'handle_patch_review: request body', error: 'InvalidRequest' },
  { status: 404, site: 'handle_patch_review: review id unmatched', error: 'NotFound' },
  { status: 500, site: 'handle_patch_review: review store write failure', error: null },
  { status: 404, site: 'handle_bulk_resolve_reviews: project resolution', error: 'NotFound' },
  { status: 400, site: 'handle_bulk_resolve_reviews: request body', error: 'InvalidRequest' },
  { status: 400, site: 'handle_bulk_resolve_reviews: empty ids array', error: 'InvalidRequest' },
  { status: 500, site: 'handle_bulk_resolve_reviews: review store write failure', error: null },
  { status: 404, site: 'handle_embed_page: project resolution', error: 'NotFound' },
  { status: 400, site: 'handle_embed_page: request JSON', error: 'InvalidRequest' },
  { status: 400, site: 'handle_embed_page: empty path', error: 'InvalidRequest' },
  { status: 400, site: 'handle_embed_page: embedding config absent', error: 'EmbedError', embedKind: 'InvalidRequest' },
  { status: 503, site: 'handle_embed_page: page embed slot exhausted', error: 'Busy' },
  {
    status: 400,
    site: 'handle_embed_page: page embed InvalidRequest',
    error: 'EmbedError',
    embedKind: 'InvalidRequest',
  },
  { status: 404, site: 'handle_embed_page: page embed NotFound', error: 'EmbedError', embedKind: 'NotFound' },
  { status: 502, site: 'handle_embed_page: page embed Provider', error: 'EmbedError', embedKind: 'Provider' },
  { status: 500, site: 'handle_embed_page: page embed Storage', error: 'EmbedError', embedKind: 'Storage' },
  { status: 409, site: 'handle_embed_page: page embed Conflict', error: 'EmbedError', embedKind: 'Conflict' },
  { status: 504, site: 'handle_embed_page: page embed Timeout', error: 'EmbedError', embedKind: 'Timeout' },
  { status: 404, site: 'handle_search: project resolution', error: 'NotFound' },
  { status: 400, site: 'handle_search: request JSON', error: 'InvalidRequest' },
  { status: 400, site: 'handle_search: empty query', error: 'InvalidRequest' },
  { status: 400, site: 'handle_search: query embedding resolution', error: 'EmbedError', embedKind: 'InvalidRequest' },
  { status: 500, site: 'handle_search: retrieval failure', error: null },
  { status: 404, site: 'prepare_chat: project resolution', error: 'NotFound' },
  { status: 400, site: 'prepare_chat: request JSON', error: 'InvalidRequest' },
  { status: 400, site: 'handle_chat: empty message', error: 'InvalidRequest' },
  { status: 499, site: 'handle_chat: agent turn cancelled', error: 'ChatCancelled' },
  { status: 502, site: 'handle_chat: agent runtime failure', error: 'AgentError' },
  { status: 404, site: 'handle_cancel_chat: project resolution', error: 'NotFound' },
  { status: 404, site: 'handle_graph: project resolution', error: 'NotFound' },
  { status: 500, site: 'handle_graph: graph build failure', error: null },
  { status: 404, site: 'handle_rescan: project resolution', error: 'NotFound' },
  { status: 500, site: 'handle_rescan: rescan failure', error: null },
  { status: null, site: 'start_api_server: bind retries exhausted (api_status port_conflict)', error: 'BindConflict' },
  { status: null, site: 'apps/mcp-server assertMcpEnabled (adapter-side gate today)', error: 'McpDisabled' },
]
